export type HeroMascotLayer = "background" | "middle" | "foreground"

export type HeroMascotAnimation = "drift-a" | "drift-b" | "drift-c" | "drift-d"

export type HeroMascotConfig = {
  id: string
  src: string
  alt: string
  layer: HeroMascotLayer
  zIndex: number
  width: number
  top?: string
  left?: string
  right?: string
  bottom?: string
  rotate: number
  parallaxStrength: number
  scrollFactor: number
  animation: HeroMascotAnimation
  animationDelay: number
  animationDuration: number
  priority?: boolean
  centerX?: boolean
}

const base = (id: string, alt: string) => `/hero/mascots/${id}.webp`

export const HERO_MASCOTS_DESKTOP: HeroMascotConfig[] = [
  {
    id: "black-gorilla",
    src: base("black-gorilla"),
    alt: "Black gorilla mascot",
    layer: "background",
    zIndex: 4,
    width: 340,
    left: "-4%",
    bottom: "2%",
    rotate: -4,
    parallaxStrength: 0.35,
    scrollFactor: 0.08,
    animation: "drift-b",
    animationDelay: 0.4,
    animationDuration: 17,
  },
  {
    id: "white-wolf",
    src: base("white-wolf"),
    alt: "White wolf mascot",
    layer: "background",
    zIndex: 5,
    width: 220,
    right: "2%",
    top: "14%",
    rotate: 6,
    parallaxStrength: 0.3,
    scrollFactor: 0.06,
    animation: "drift-c",
    animationDelay: 1.1,
    animationDuration: 19,
  },
  {
    id: "black-wolf",
    src: base("black-wolf"),
    alt: "Black wolf mascot",
    layer: "background",
    zIndex: 6,
    width: 210,
    left: "6%",
    top: "18%",
    rotate: -5,
    parallaxStrength: 0.32,
    scrollFactor: 0.07,
    animation: "drift-a",
    animationDelay: 0.7,
    animationDuration: 16,
  },
  {
    id: "boxing-bear",
    src: base("boxing-bear"),
    alt: "Boxing bear mascot",
    layer: "middle",
    zIndex: 10,
    width: 260,
    right: "14%",
    top: "10%",
    rotate: 3,
    parallaxStrength: 0.55,
    scrollFactor: 0.12,
    animation: "drift-d",
    animationDelay: 0.2,
    animationDuration: 15,
  },
  {
    id: "tiger",
    src: base("tiger"),
    alt: "Tiger mascot",
    layer: "middle",
    zIndex: 11,
    width: 250,
    left: "16%",
    bottom: "6%",
    rotate: -2,
    parallaxStrength: 0.6,
    scrollFactor: 0.14,
    animation: "drift-c",
    animationDelay: 0.9,
    animationDuration: 14,
  },
  {
    id: "tan-bear",
    src: base("tan-bear"),
    alt: "Tan bear mascot",
    layer: "middle",
    zIndex: 12,
    width: 210,
    left: "32%",
    bottom: "0%",
    rotate: 1,
    parallaxStrength: 0.65,
    scrollFactor: 0.15,
    animation: "drift-b",
    animationDelay: 1.4,
    animationDuration: 18,
  },
  {
    id: "pink-panda",
    src: base("pink-panda"),
    alt: "Pink panda mascot",
    layer: "middle",
    zIndex: 13,
    width: 200,
    right: "30%",
    bottom: "14%",
    rotate: -3,
    parallaxStrength: 0.58,
    scrollFactor: 0.13,
    animation: "drift-a",
    animationDelay: 0.5,
    animationDuration: 16,
  },
  {
    id: "pink-teddy",
    src: base("pink-teddy"),
    alt: "Pink teddy mascot",
    layer: "foreground",
    zIndex: 20,
    width: 230,
    right: "24%",
    bottom: "10%",
    rotate: 2,
    parallaxStrength: 0.85,
    scrollFactor: 0.2,
    animation: "drift-d",
    animationDelay: 0.3,
    animationDuration: 13,
  },
  {
    id: "red-panda",
    src: base("red-panda"),
    alt: "Red panda mascot",
    layer: "foreground",
    zIndex: 22,
    width: 175,
    left: "2%",
    bottom: "12%",
    rotate: -6,
    parallaxStrength: 0.9,
    scrollFactor: 0.22,
    animation: "drift-b",
    animationDelay: 1.2,
    animationDuration: 15,
  },
  {
    id: "polar-bear",
    src: base("polar-bear"),
    alt: "Polar bear mascot",
    layer: "foreground",
    zIndex: 30,
    width: 380,
    right: "4%",
    bottom: "-2%",
    rotate: -1,
    parallaxStrength: 1,
    scrollFactor: 0.25,
    animation: "drift-a",
    animationDelay: 0,
    animationDuration: 14,
    priority: true,
  },
]

export const HERO_MASCOTS_TABLET: HeroMascotConfig[] = [
  {
    id: "black-gorilla",
    src: base("black-gorilla"),
    alt: "Black gorilla mascot",
    layer: "background",
    zIndex: 4,
    width: 240,
    left: "-6%",
    bottom: "0%",
    rotate: -3,
    parallaxStrength: 0.25,
    scrollFactor: 0.06,
    animation: "drift-b",
    animationDelay: 0.5,
    animationDuration: 18,
  },
  {
    id: "black-wolf",
    src: base("black-wolf"),
    alt: "Black wolf mascot",
    layer: "background",
    zIndex: 5,
    width: 160,
    right: "4%",
    top: "16%",
    rotate: 4,
    parallaxStrength: 0.22,
    scrollFactor: 0.05,
    animation: "drift-c",
    animationDelay: 0.8,
    animationDuration: 17,
  },
  {
    id: "tiger",
    src: base("tiger"),
    alt: "Tiger mascot",
    layer: "middle",
    zIndex: 10,
    width: 190,
    left: "8%",
    bottom: "8%",
    rotate: -2,
    parallaxStrength: 0.45,
    scrollFactor: 0.1,
    animation: "drift-a",
    animationDelay: 0.3,
    animationDuration: 15,
  },
  {
    id: "pink-teddy",
    src: base("pink-teddy"),
    alt: "Pink teddy mascot",
    layer: "middle",
    zIndex: 12,
    width: 170,
    right: "18%",
    bottom: "12%",
    rotate: 2,
    parallaxStrength: 0.5,
    scrollFactor: 0.11,
    animation: "drift-d",
    animationDelay: 0.6,
    animationDuration: 14,
  },
  {
    id: "red-panda",
    src: base("red-panda"),
    alt: "Red panda mascot",
    layer: "foreground",
    zIndex: 18,
    width: 140,
    left: "0%",
    bottom: "10%",
    rotate: -5,
    parallaxStrength: 0.65,
    scrollFactor: 0.15,
    animation: "drift-b",
    animationDelay: 1,
    animationDuration: 16,
  },
  {
    id: "polar-bear",
    src: base("polar-bear"),
    alt: "Polar bear mascot",
    layer: "foreground",
    zIndex: 25,
    width: 300,
    right: "0%",
    bottom: "-1%",
    rotate: -1,
    parallaxStrength: 0.75,
    scrollFactor: 0.18,
    animation: "drift-a",
    animationDelay: 0,
    animationDuration: 14,
    priority: true,
  },
]

export const HERO_MASCOTS_MOBILE: HeroMascotConfig[] = [
  {
    id: "black-gorilla",
    src: base("black-gorilla"),
    alt: "Black gorilla mascot",
    layer: "background",
    zIndex: 4,
    width: 150,
    left: "-8%",
    bottom: "4%",
    rotate: -4,
    parallaxStrength: 0,
    scrollFactor: 0.04,
    animation: "drift-b",
    animationDelay: 0.6,
    animationDuration: 20,
  },
  {
    id: "tiger",
    src: base("tiger"),
    alt: "Tiger mascot",
    layer: "middle",
    zIndex: 10,
    width: 120,
    right: "-4%",
    bottom: "18%",
    rotate: 3,
    parallaxStrength: 0,
    scrollFactor: 0.06,
    animation: "drift-c",
    animationDelay: 0.4,
    animationDuration: 18,
  },
  {
    id: "red-panda",
    src: base("red-panda"),
    alt: "Red panda mascot",
    layer: "foreground",
    zIndex: 16,
    width: 95,
    left: "-2%",
    bottom: "14%",
    rotate: -4,
    parallaxStrength: 0,
    scrollFactor: 0.08,
    animation: "drift-a",
    animationDelay: 0.9,
    animationDuration: 17,
  },
  {
    id: "polar-bear",
    src: base("polar-bear"),
    alt: "Polar bear mascot",
    layer: "foreground",
    zIndex: 22,
    width: 240,
    left: "50%",
    bottom: "-2%",
    rotate: 0,
    parallaxStrength: 0,
    scrollFactor: 0.1,
    animation: "drift-a",
    animationDelay: 0,
    animationDuration: 16,
    priority: true,
    centerX: true,
  },
]

export function getHeroMascotsForWidth(width: number): HeroMascotConfig[] {
  if (width >= 1200) return HERO_MASCOTS_DESKTOP
  if (width >= 768) return HERO_MASCOTS_TABLET
  return HERO_MASCOTS_MOBILE
}
